### ISSUE TITLE
Throws I2C Exception on PyBadge LC

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_PyBadger#4]
The accelerometer is not included on the LC which causes the constructor to throw an exception. We should detect which board it is and only init the relevant things. Don't catch the exception because then other errors may be hidden.

**Comment by darrell24015** [comment]
Same issue with my two PyBadge LCs. I'll be glad to beta test anything in the process to work on a fix.

**Comment by ladyada** [comment]
@makermelissa heya kattni is out of town, do you want to look at this and create a fix?

**Comment by makermelissa** [comment]
Do either of you have the exact error message? I don't have any PyBadge LCs on hand and that would help me out. Thanks.

**Comment by makermelissa** [comment]
@darrell24015, if you would like to test #5, that would be appreciated. Thanks

**Comment by darrell24015** [comment]
> Do either of you have the exact error message? I don't have any PyBadge LCs on hand and that would help me out. Thanks.

Here's the error I was getting:
"File adafruit_pybadger.py line 87 RuntimeError SDA or SCL needs a pull-up"

**Comment by darrell24015** [comment]
> @darrell24015, if you would like to test #5, that would be appreciated. Thanks

I will give this a try tonight and report back. Thanks!

**Comment by darrell24015** [comment]
:+1:  It works! No RuntimeError like before.  I can see all three screens (Button A, B or Start). :1st_place_medal:

**Comment by darrell24015** [comment]
Without accelerometer data, the screen dims straight away. That's not really an issue, just an observation. I'm looking through the API docs to see if there's something to adjust the screen brightness - maybe a button press? Otherwise, it's running on the PyBadge LC - woohoo! :champagne:

**Comment by makermelissa** [comment]
Good catch Darrell. I'll see if I can disable screen dimming if there's no accelerometer detected.

**Comment by makermelissa** [comment]
On second thought, it may make more sense for the user to just to remove the line:
```
pybadger.auto_dim_display(delay=10)
```
from the example before running it. I think I'll add a comment for the user to remove.

**Comment by darrell24015** [comment]
> it may make more sense for the user to just to remove the line

Was there any thought about using the A7 Light sensor for input to dim the screen when ambient light is low?  Just a thought.  I was thinking more along the lines of using the Up/Down buttons to adjust brightness. Again, this is slightly off-topic.   Another thought, this eventually gets compiled to a .mpy file in the Library download, so end-user won't be able to edit - correct?

**Comment by makermelissa** [comment]
Regarding the Light Sensor usage, this is an eventual goal with Circuit Python to adjust the brightness automatically in different light conditions, so we didn't want to add it in from this side.

The .mpy files are smaller and are an option, but you can also run with the uncompiled scripts, so the user could edit. The button adjustments sounds more like a new feature and maybe you could add that as an issue. PR #5 was just to address it crashing on the PyBadge LC.
