### ISSUE TITLE
Duplicate code in library files - potential refactor needed

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_PyBadger#42]
Failure can be found [here](https://github.com/adafruit/Adafruit_CircuitPython_PyBadger/pull/41/checks?check_run_id=2007426342).

We want to avoid having duplicate code in multiple library files. A way around this is to refactor as much as possible into a base file and use that within the other files.

**Comment by evaherrada** [comment]
Moving to new issue
