### ISSUE TITLE
Remove use of GamePad and GamePadShift

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_PyBadger#44]
[#4940](https://github.com/adafruit/circuitpython/pull/4940) in the core will remove gamepad and gamepadshift.

This library makes use of these objects to handle the buttons for some of the devices that are supported. We'll need to change over this library to use the newer keypad functionality when these do get removed from the core.

**Comment by caternuson** [comment]
yep:
https://forums.adafruit.com/viewtopic.php?f=65&t=183536

**Comment by FoamyGuy** [comment]
#48 (marked as draft currently) implements this change.

**Comment by FoamyGuy** [comment]
closed by #48
