### ISSUE TITLE
Type annotation corrections needed

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_PyBadger#62]
This library needs type annotation improvements!  It mistakenly uses `Type[tuple]` where there are `namedtuple` returns.  For example:

```python
from collections import namedtuple

NamedTupleClass = namedtuple("NamedTupleClass", ("A", "B", "C"))
```

Then if a function use a type annotation like `Type[tuple]`:

```python
def some_method(arg_a: str, arg_b: int) -> Type[tuple]:
    return NamedTupleClass(1, 2, 3)
```

It should actually be:

```python
def some_method(arg_a: str, arg_b: int) -> NamedTupleClass:
    return NamedTupleClass(1, 2, 3)
```

**Comment by Jayaram18** [comment]
Hi @tekktrik ,
      I would like to work on this issue.

**Comment by tekktrik** [comment]
Sure thing!  Let me know if I can help with anything!

**Comment by tekktrik** [comment]
Hey @Jayaram18 anything I can help with?
