### ISSUE TITLE
Issue specifying font through show_badge

### ISSUE THREAD

**Issue by ericklein** [adafruit/Adafruit_CircuitPython_PyBadger#9]
when passing a .bdf font through pybadger.show_badge

pybadger.show_badge(hello_string="Ola!", name_string="Blinka", hello_font="Helvetica-Bold-16.bdf", hello_scale=2, my_name_is_scale=1, name_scale=2)

causes the following exception:

Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "adafruit_pybadger.py", line 332, in show_badge
  File "adafruit_display_text/label.py", line 73, in __init__
AttributeError: 'str' object has no attribute 'get_bounding_box'

I've tested with the adafruit generated fonts Helvetica-Bold-16.bdf and Noto-18.bdf, both which work when using:

name_font = bitmap_font.load_font(name_font_name)
name_font.load_glyphs(NAME_STRING.encode('utf-8'))

I also renamed *.bdf to *.FONT on the off chance that the libraries were looking for that extension, as in the example terminalio.FONT, but that did not change the exception returned.

**Comment by makermelissa** [comment]
Yeah, I saw that issue when I was playing around with it at SuperCon. It's throwing that error because it's expecting a bitmap font rather than a string. You can check this guide (https://learn.adafruit.com/pybadge-conference-badge-multi-language-unicode-fonts/setup) out how to do that. However, I think a string would be much easier though, so I'm going to leave this open.

**Comment by ericklein** [comment]
I passed Noto-18.bdf to pybadger.show_badge using:

name_font_name = "/fonts/Noto-18.bdf"
name_font = bitmap_font.load_font(name_font_name)
name_font.load_glyphs(MY_NAME_STRING.encode('utf-8'))

and it works!, but the onscreen position is incorrect. 
![badge_bug](https://user-images.githubusercontent.com/6754224/69466744-29df8480-0d3a-11ea-927f-47f3371c4a91.jpg)

The name is displayed between the bottom of the white "name box" and the red lower border. Another Adafruit example for the name code uses:

name_label = Label(name_font, text=NAME_STRING, line_spacing=0.75)
(x, y, w, h) = name_label.bounding_box
name_label.x = (80 - w // 2)
name_label.y = 85
name_label.color = FOREGROUND_TEXT_COLOR
splash.append(name_label)

but this other technique uses literal, fixed positioning :(

**Comment by makermelissa** [comment]
Yeah, that definitely needs fixing. The PyBadger library was based on the other example with the fixed positioning, but I think it need a little correcting. I think fixing the positioning and passing the font as a string would be great features for this.
